# Generated by Django 3.1.4 on 2023-12-17 13:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import website.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_button_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_button_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_button_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_contact_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_contact_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_contact_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_image', models.ImageField(upload_to='Website')),
                ('solutions_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_solutions_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('about_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_about_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('about_text', ckeditor.fields.RichTextField(default='')),
                ('arabic_about_text', ckeditor.fields.RichTextField(default='')),
                ('about_image', models.ImageField(upload_to='Website')),
                ('company_profile', models.FileField(upload_to='files')),
                ('vision_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_vision_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vision_text', ckeditor.fields.RichTextField(default='')),
                ('arabic_vision_text', ckeditor.fields.RichTextField(default='')),
                ('vision_image', models.ImageField(upload_to='Website')),
                ('mission_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_mission_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mission_text', ckeditor.fields.RichTextField(default='')),
                ('arabic_mission_text', ckeditor.fields.RichTextField(default='')),
                ('mission_image', models.ImageField(upload_to='Website')),
                ('values_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_values_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('values_supporting_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_values_supporting_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('services_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_services_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('services_supporting_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_services_supporting_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('qualities_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_qualities_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('industries_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_industries_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('contact_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_contact_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('whatsapp_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_form_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_name_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_email_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('message_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_message_placeholder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_button', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_send_button', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon', models.FileField(upload_to='image', validators=[website.utils.validate_image_and_svg_file_extension])),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='website.homepagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon', models.FileField(upload_to='image', validators=[website.utils.validate_image_and_svg_file_extension])),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='website.homepagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon', models.FileField(upload_to='image', validators=[website.utils.validate_image_and_svg_file_extension])),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='website.homepagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(default='')),
                ('arabic_text', ckeditor.fields.RichTextField(default='')),
                ('image', models.ImageField(upload_to='Website')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='website.homepagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon', models.FileField(upload_to='image', validators=[website.utils.validate_image_and_svg_file_extension])),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='website.homepagedata')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='website.homepagedata')),
            ],
        ),
    ]
