# Generated by Django 3.1.4 on 2023-12-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20231217_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='arabic_company_profile',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerlink',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.homepagedata'),
        ),
    ]
