# Generated by Django 3.1.4 on 2023-12-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20231218_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedata',
            name='arabic_company_profile',
        ),
    ]
