# Generated by Django 3.1.4 on 2023-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_homepagedata_arabic_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='snapchat_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='twitter_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagedata',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
