# Generated by Django 3.1.4 on 2023-12-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20231225_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedata',
            name='snapchat_link',
        ),
    ]
