# Generated by Django 3.1.4 on 2024-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_homepagedata_snapchat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='arabic_company_profile',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
