# Generated by Django 3.1.4 on 2024-07-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_homepagedata_arabic_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppsPageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landing_image', models.ImageField(upload_to='Website')),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('english_description', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('apps_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='apps_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.appspagedata'),
        ),
    ]
