# Generated by Django 3.1.4 on 2024-08-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20240731_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videodata',
            name='apps_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.applicationcategory'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
