# Generated by Django 3.1.4 on 2024-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20240801_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodata',
            old_name='english_description',
            new_name='arabic_description',
        ),
        migrations.RenameField(
            model_name='videodata',
            old_name='english_title',
            new_name='arabic_title',
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='arabic_description',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='arabic_headline',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
