# Generated by Django 3.1.4 on 2024-08-01 09:09

from django.db import migrations, models
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20240801_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video', validators=[website.utils.validate_video_file_extension]),
        ),
    ]
