# Generated by Django 3.1.4 on 2024-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_videodata_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos'),
        ),
    ]
