# Generated by Django 3.1.4 on 2024-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_videodata_video_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
