# Generated by Django 3.1.4 on 2024-08-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20240805_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arabic_button_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
