# Generated by Django 3.1.4 on 2024-08-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_service_arabic_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerlink',
            name='homepage',
        ),
    ]
