# Generated by Django 3.1.4 on 2024-08-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_headerlink_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('whatsapp_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facebook_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='headerlink',
            name='global_data',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.globaldata'),
        ),
    ]
