# Generated by Django 3.1.4 on 2024-08-25 08:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0017_auto_20240825_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishLandingHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicLandingHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishLandingSubheadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicLandingSubheadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishReadyText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicReadyText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('registerButtonUrl', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishRegisterButtonText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicRegisterButtonText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landingBackground', models.FileField(upload_to='images')),
                ('englishTargetAudienceHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicTargetAudienceHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishTargetAudienceText', ckeditor.fields.RichTextField(default='')),
                ('arabicTargetAudienceText', ckeditor.fields.RichTextField(default='')),
                ('englishGoalsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicGoalsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishOutputsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicOutputsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('outputsImage', models.FileField(upload_to='images')),
                ('englishCoursesHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicCoursesHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishJobsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicJobsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishJobsText', ckeditor.fields.RichTextField(default='')),
                ('arabicJobsText', ckeditor.fields.RichTextField(default='')),
                ('jobsImage', models.FileField(upload_to='images')),
                ('englishConditionsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicConditionsHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicFaqHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishFaqHeadline', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='targetAudiencesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audiences', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='programInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images')),
                ('arabicInfoLabel', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishInfoLabel', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicInfoText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('englishInfoText', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_info', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='outputsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishOutput', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicOutput', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='goalsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images')),
                ('englishGoalText', ckeditor.fields.RichTextField(default='')),
                ('arabicGoalText', ckeditor.fields.RichTextField(default='')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='faqsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishQuestion', ckeditor.fields.RichTextField(default='')),
                ('arabicQuestion', ckeditor.fields.RichTextField(default='')),
                ('englishAnswer', ckeditor.fields.RichTextField(default='')),
                ('arabicAnswer', ckeditor.fields.RichTextField(default='')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='coursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishTitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabicTitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='website.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='conditionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images')),
                ('englishText', ckeditor.fields.RichTextField(default='')),
                ('arabicText', ckeditor.fields.RichTextField(default='')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='website.homepage')),
            ],
        ),
    ]
