# Generated by Django 3.1.4 on 2024-08-25 11:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20240825_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_subheadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_landing_subheadline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_landing_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_intro_text', ckeditor.fields.RichTextField(default='')),
                ('arabic_intro_text', ckeditor.fields.RichTextField(default='')),
                ('landing_cover_image', models.FileField(upload_to='images')),
                ('english_submit_button', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_submit_button', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_in_progress_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_in_progress_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_success_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_success_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_failed_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_failed_text', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_headline', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_input_label', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_input_label', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sanity_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('input_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='website.formsections')),
            ],
        ),
    ]
