# Generated by Django 3.1.4 on 2024-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_formfields_formpage_formsections'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
