# Generated by Django 3.2 on 2024-08-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_formfields_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_officer_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('training_officer_job', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('training_officer_phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_sex', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_civil_registry', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_birth_date', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_qualification', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_qualification_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_graduation_year', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_job_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_email_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_nomination_letter', models.FileField(blank=True, null=True, upload_to='images')),
                ('candidate_bachelor_document', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
