# Generated by Django 3.2 on 2024-08-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_footer_license', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_footer_license', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('arabic_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('header_footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='website.headerfooter')),
            ],
        ),
    ]
