# Generated by Django 3.2 on 2024-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_headerfooter_headerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='sanity_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, null=True),
        ),
    ]
